server {
    listen 80;
    server_name _;

    # Отдаём фронтенд (через frontend-service)
    location / {
        proxy_pass http://frontend-service:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Проксируем API на api-gateway-service
    location /api/ {
        proxy_pass http://api-gateway-service:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Проксируем WireMock (для отладки)
    location /wiremock/ {
        proxy_pass http://wiremock:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
