spring.application.name=authTrucking


#import from .env file
spring.config.import=optional:file:.env[.properties]
server.port=8080
#DB config
spring.datasource.url=${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

