spring.application.name=authTrucking


#import from .env file
spring.config.import=optional:file:.env[.properties]
server.port=8080
#DB config
spring.datasource.url=${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:your-email@gmail.com}
spring.mail.password=${MAIL_PASSWORD:your-app-password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# docker profile (используется в контейнере)
spring.config.activate.on-profile=docker
server.port=8080
spring.datasource.url=jdbc:postgresql://postgres:5432/appdb
spring.datasource.username=appuser
spring.datasource.password=apppassword

