server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Single Page Application – все роуты на index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Статика
    location /assets/ {
        try_files $uri $uri/ =404;
    }
}
